SET IDENTITY_INSERT [dbo].[Noticias] ON
INSERT INTO [dbo].[Noticias] ([Id], [Titulo], [Body], [Data], [CategoriaFK], [FotografiaFK], [JornalistaFK]) VALUES (4, N'MODRIC SOBRE MBAPPÉ: «TERÁ DE VIVER COM ESSA DECISÃO»', N'Kylian Mbappé decidiu renovar pelo Paris Saint-Germain e recusar a proposta do Real Madrid. Luka Modric respeita a decisão do avançado francês, mas alerta que agora terá de viver com ela. «Mbappé decidiu o que decidiu e estava no seu direito. Agora terá que viver com essa decisão. Todos pensávamos que ia acontecer e não foi assim. Vamos fazer o quê? Também não é preciso crucificar Mbappé… É um grande jogador, mas como sempre digo e repito, ninguém é mais importante que o clube. O Real Madrid é maior, está acima de todos e será sempre assim», disse o médio, em entrevista ao Sportske. Modric pediu a camisola de Mbappé durante o jogo entre as duas equipas para a Champions e causou polémica: «Não estou arrependido. Foi um pedido que me tinham feito.»', N'2022-07-02 15:34:55', 4, 4, 1)
INSERT INTO [dbo].[Noticias] ([Id], [Titulo], [Body], [Data], [CategoriaFK], [FotografiaFK], [JornalistaFK]) VALUES (6, N'Chamas consomem mato em zona residencial de Algueirão-Mem Martins, Sintra', N'Um incêndio deflagrou na tarde deste sábado numa zona de mato junto a habitações, na Tapada das Mercês, freguesia de Algueirão-Mem Martins, em Sintra. 
O alerta foi dado pelas 14h35. 
No local estão 57 operacionais, 15 meios terrestres e um meio aéreo. ', N'2022-07-02 15:38:53', 1, 5, 2)
INSERT INTO [dbo].[Noticias] ([Id], [Titulo], [Body], [Data], [CategoriaFK], [FotografiaFK], [JornalistaFK]) VALUES (7, N'Preço dos combustíveis baixa na segunda-feira', N'Os combustíveis vão baixar de preço na próxima segunda-feira. A alteração será mais expressiva no gasóleo, cujo valor cobrado por litro deverá diminuir oito cêntimos, enquanto a gasolina poderá descer três cêntimos, de acordo com fontes do setor.

Tendo por base a informação recolhida pela Direção-Geral de Energia e Geologia, o preço médio por litro do gasóleo simples a nível nacional foi, ao longo desta semana, de cerca de dois euros, pelo que a partir de segunda-feira deverá baixar, em termos médios, para cerca de 1,92 euros. Já a gasolina simples 95 poderá cair dos 2,1 euros por litro para cerca de 2,07 euros.

O desconto no Imposto sobre os Produtos Petrolíferos (ISP) equivalente a uma descida da taxa do IVA dos 23% para os 13% vai manter-se nos meses de julho e agosto, anunciou esta sexta-feira o Ministério das Finanças.

Tendo em conta as medidas criadas pelo Governo para mitigar a subida dos preços dos combustíveis, a diminuição da carga fiscal será de 28,2 cêntimos por litro de gasóleo e de 32,1 cêntimos por litro de gasolina. Este desconto será reavaliado em agosto.', N'2022-07-02 15:40:38', 3, 6, 3)
SET IDENTITY_INSERT [dbo].[Noticias] OFF
